### ISSUE TITLE
Buttons Stop Working On Change Until Relaunch

### ISSUE THREAD

**Issue by mediamanrit** [logicallysound/streamdeck-discord-message#10] opened 2020-06-24 14:01 UTC
When I create a new button or change an existing button, the button does not work until I restart the Stream Deck app.  This is on the latest version (1.1.0).

**Comment by nosut** [comment] 2020-09-28 02:20
Just started using this. Reporting the same issues here. Personally not a big deal. May want to make note of it for new users.

**Comment by logicallysound** [comment] 2020-10-06 19:55
Not 100% sure but this may be a dupe of #9

**Comment by logicallysound** [comment] 2020-10-07 06:41
Yeah, pretty sure this is a #9 dupe

**Closed as completed by logicallysound** 2020-10-07 06:41 UTC
Labels: bug, duplicate
